# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackathonChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'lottie-ios'
  pod 'R.swift'

end
